language: node_js

matrix:
  include:
  - node_js: '8'

script:
- validate-commit-msg "$(git log -1 --pretty=%B)" && npm test

notifications:
  email: false

before_install: ".travis/before_install.sh"
after_success: ".travis/after_success.sh"
